config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destory]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
      if @article.save
        flash[:notice] = "Article was successfully created."
        redirect_to @article
      else
        render 'new'
      end
    end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
      if @article.update(article_params)
        flash[:notice] = "Article was successfully updated"
        redirect_to @article
      else
        render 'edit'
      end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
      flash[:notice] = "Article was successfully destroyed."
      redirect_to articles_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids:[])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] ="You can only edit or delete your own article"
        redirect_to @article
      end
    end

  end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container ">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <%end%>
            <% if article.categories.any?%>
              <div class="mt-2"><%= render article.categories %></div>
            <%end%>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), id: "text-article" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success"%>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info"%>
              <%= link_to "Delete", article, method: :delete, class: "btn btn-outline-danger"%>
            <%end%>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(article.created_at)%> ago,
             edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/articles/_form.html.erb
<div class="container row justify-content-center">
  <div class= "col-10">
    <%= render 'shared/errors', obj:article %>
    <%= form_with(model: article, class: "shadow p-3 mb-3 bg-black rounded justify-content-center", local: true) do |form| %>

      <div class="form-group row">
        <%= form.label :title, class: "col-2 col-form-label text-white" %>
        <div class ="col-10">
          <%= form.text_field :title, class: "form-control", placeholder: "Title of article" %>
        </div>
      </div>
      <br>
      <div class="form-group row mb-2">
        <%= form.label :description, class: "col-2 col-form-label text-white" %>
        <div class ="col-10">
          <%= form.text_area :description, rows:10, class: "form-control", placeholder: "Description of article"  %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :category, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= form.collection_select(:category_ids, Category.all, :id, :name,
          { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select" }) %>
        </div>
      </div>


      <div class="form-group row justify-content-center">
        <%= form.submit class: "btn btn-outline-light btn-lg col-3"%>
      </div>
    <% end %>
  </div>
  <div class="mb-3 text-center">
    <%= link_to "Back to articles", articles_path, class: "text-black"%>
  </div>
</div>

app/views/articles/edit.html.erb
<div class= "container justify-content-md-center">

  <h1 class="text-center mt-4">Edit Article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing Articles</h1>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<%= render 'article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div class= "container justify-content-md-center">
  <h1 class="text-center mt-4">New Article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<div class= "container justify-content-md-center">
    <h2 class="text-center mt-4"><%=@article.title%></h2>
    <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header font-italic">
                by <%= @article.user.username if @article.user %>
                <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
                <% if @article.categories.any?%>
                  <div class="mt-2"><%= render @article.categories %></div>
                <%end%>
              </div>
              <div class="card-body">
                <div class="card-text text-start">
                  <%= simple_format(@article.description)%>
                </div>
                <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
                  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info"%>
                  <%= link_to "Delete", @article, method: :delete, class: "btn btn-outline-danger"%>
                <%end%>
              </div>
              <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(@article.created_at)%> ago,
                 edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
              </div>
            </div>
          </div>
        </div>
    </div>

  </div>