config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :require_admin, except: [:index, :show]
  # GET /categories or /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
      if @category.update(category_params)
        flash[:notice] = "Category was successfully updated"
        redirect_to @category
      else
        render 'edit'
      end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
      flash[:notice] = "Category was successfully destroyed."
      redirect_to categories_url

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge bg-dark mr-1" %>

app/views/categories/_form.html.erb
<div class="container row justify-content-center">
  <div class= "col-10">
    <%= render 'shared/errors', obj:@category %>
    <%= form_with(model:@category, class: "shadow p-3 mb-3 bg-black rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
        <div class ="col-10">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter a name" %>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg col-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class= "container justify-content-md-center">
  <h1 class="text-center mt-4">Edit category name</h1>
  <%= render 'form'%>
  <div class="mb-3 text-center">
    <%= link_to "Back to category", category_path(@category), class: "text-black"%>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container ">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%=link_to category.name, category_path(category), id: "text-article" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(category.created_at)%> ago,
             edited <%= time_ago_in_words(category.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div class= "container justify-content-md-center">
  <h1 class="text-center mt-4">Create a new category</h1>
  <%= render 'form'%>
  <div class="mb-3 text-center">
    <%= link_to "Back to categories", categories_path, class: "text-black"%>
  </div>
</div>

app/views/categories/show.html.erb
<div class= "container justify-content-md-center">

<h1 class="text-center mt-4">Category: <%= @category.name%></h1>

<% if logged_in? && current_user.admin?%>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info"%>
  </div>
<%end%>

<h3 class="text-center mt-4">Articles</h3>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

</div>