config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Haya Aljuraysi", "https://www.github.com/hayanj", class: "text-white"%></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|%>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg%>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Haya's blog", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in?%>
              <li><%= link_to "Create new article", new_article_path, class: "dropdown-item"%> </li>
            <%end%>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin?%>
              <li><%= link_to "Create new category", new_category_path, class: "dropdown-item"%> </li>
            <%end%>
            <li><%= link_to "View categories", categories_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>

        <%if logged_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%="(Admin)" if current_user.admin?%> Profile [<%=current_user.username%>]
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item"%> </li>
            <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item"%></li>
            <li><%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" }%></li>
          </ul>
        </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>